/*
 * Java domain class for entity "TtrnClaimDetails" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:14 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:43:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TtrnClaimDetails;
import com.maan.insurance.model.entity.TtrnClaimDetailsId;
/**
 * <h2>TtrnClaimDetailsRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:43:14
 * <p>
 * Description: "TtrnClaimDetails" Repository
 */
 
 
 
public interface TtrnClaimDetailsRepository  extends JpaRepository<TtrnClaimDetails,TtrnClaimDetailsId > , JpaSpecificationExecutor<TtrnClaimDetails> {

	long countByContractNoAndLayerNo(String proposalNo, BigDecimal layerNo);

}
