/*
 * Java domain class for entity "TtrnPaymentReceiptDetails" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:59 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:43:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TtrnPaymentReceiptDetails;
import com.maan.insurance.model.entity.TtrnPaymentReceiptDetailsId;
/**
 * <h2>TtrnPaymentReceiptDetailsRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:43:59
 * <p>
 * Description: "TtrnPaymentReceiptDetails" Repository
 */
 
 
 
public interface TtrnPaymentReceiptDetailsRepository  extends JpaRepository<TtrnPaymentReceiptDetails,TtrnPaymentReceiptDetailsId > , JpaSpecificationExecutor<TtrnPaymentReceiptDetails> {

}
