/*
 * Created on 2022-09-15 ( 15:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.insurance.model.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "TtrnMndInstallments" ( stored in table "TTRN_MND_INSTALLMENTS" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TtrnMndInstallmentsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal installmentNo ;
    
    private String     proposalNo ;
    
   // private String     contractNo ;
    
    private BigDecimal endorsementNo ;
    
     
}
