/*
 * Created on 2022-09-15 ( 15:43:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.insurance.model.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "TtrnPaymentReceiptDetails" ( stored in table "TTRN_PAYMENT_RECEIPT_DETAILS" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TtrnPaymentReceiptDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal receiptNo ;
    
    private BigDecimal receiptSlNo ;
    
    private BigDecimal amendId ;
    
     
}
