/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:58 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:43:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "TtrnPaymentReceiptDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TtrnPaymentReceiptDetailsId.class)
@Table(name="TTRN_PAYMENT_RECEIPT_DETAILS")


public class TtrnPaymentReceiptDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="RECEIPT_NO", nullable=false)
    private BigDecimal receiptNo ;

    @Id
    @Column(name="RECEIPT_SL_NO", nullable=false)
    private BigDecimal receiptSlNo ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CURRENCY_ID")
    private BigDecimal currencyId ;

    @Column(name="AMOUNT")
    private BigDecimal amount ;

    @Column(name="EXCHANGE_RATE")
    private BigDecimal exchangeRate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TRANS_DATE", nullable=false)
    private Date       transDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=1)
    private String     remarks ;

    @Column(name="ALLOCATED_TILL_DATE")
    private BigDecimal allocatedTillDate ;

    @Column(name="TOT_AMT")
    private BigDecimal totAmt ;

    @Column(name="SETTLED_EXCRATE")
    private BigDecimal settledExcrate ;

    @Column(name="CONVERTED_RECCUR")
    private BigDecimal convertedReccur ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SYS_DATE")
    private Date       sysDate ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



